# Application
spring.application.name=Ecommerce

# Database Configuration
db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=Madhu@2005
db.driver=org.postgresql.Driver

# Logging
logging.level.root=INFO
logging.level.com.ecommerce=DEBUG
