# Database Configuration
db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=Madhu@2005

# Driver
db.driver=org.postgresql.Driver

# Application
app.name=Ecommerce
